# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='path_to_gl',
            new_name='path_to_gl_iso',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='path_to_ro',
            new_name='path_to_gl_repo',
        ),
        migrations.AddField(
            model_name='settings',
            name='path_to_ro_iso',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='path_to_ro_repo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='url_to_repo',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
