# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeros', '0002_auto_20180530_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
