# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeros', '0003_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='entire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='packages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='repo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='tag',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
