# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeros', '0005_auto_20180531_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='path_to_gl_repo',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='path_to_ro_repo',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='url_to_repo',
        ),
        migrations.AddField(
            model_name='settings',
            name='repo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='stapel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
