# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeros', '0006_auto_20180601_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
