# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeros', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildIsoSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('comment', models.TextField(max_length=250, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('dir', models.CharField(blank=True, max_length=250, null=True)),
                ('label', models.CharField(blank=True, max_length=25, null=True)),
                ('rel_name', models.CharField(blank=True, max_length=25, null=True)),
                ('rel_short_name', models.CharField(blank=True, max_length=25, null=True)),
                ('rel_ver', models.CharField(blank=True, max_length=25, null=True)),
                ('comps_file_path', models.CharField(blank=True, max_length=250, null=True)),
                ('var_file_path', models.CharField(blank=True, max_length=250, null=True)),
                ('pkgset_repos', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
