# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeros', '0009_buildiso_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildiso_log',
            name='close_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='buildiso_log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
