# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-11 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testeros', '0010_auto_20180711_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildiso_log',
            name='close_at',
            field=models.DateTimeField(null=True),
        ),
    ]
